-- DDL PostgreSQL para Tienda.
--
-- Ejecutar conectado a la base de datos destino (por ejemplo, la base
-- `postgres` de Supabase). No crea una base de datos ni usuarios; Supabase
-- ya proporciona ambos. Laravel también crea sus tablas internas mediante
-- las migraciones de Backend/database/migrations/.

BEGIN;

CREATE TABLE IF NOT EXISTS public.categoria (
    categoria_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria varchar(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.cliente (
    cliente_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(45) NOT NULL,
    correo varchar(100) NOT NULL UNIQUE,
    telefono varchar(20),
    contrasena varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.productos (
    idproductos integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_producto varchar(50) NOT NULL UNIQUE,
    nombre varchar(100) NOT NULL,
    descripcion text,
    precio numeric(10, 2) NOT NULL CHECK (precio >= 0),
    stock integer NOT NULL DEFAULT 0 CHECK (stock >= 0),
    categoria_id integer NOT NULL,
    image_url text,
    CONSTRAINT productos_categoria_id_fkey
        FOREIGN KEY (categoria_id)
        REFERENCES public.categoria (categoria_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS public.pedidos (
    idpedidos integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id integer,
    fecha timestamp(0) without time zone NOT NULL,
    total numeric(10, 2) NOT NULL CHECK (total >= 0),
    CONSTRAINT pedidos_cliente_id_fkey
        FOREIGN KEY (cliente_id)
        REFERENCES public.cliente (cliente_id)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS public.detalles_pedido (
    detalles_pedido_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idpedidos integer NOT NULL,
    idproductos integer NOT NULL,
    cantidad integer NOT NULL CHECK (cantidad > 0),
    precio_unitario numeric(10, 2) NOT NULL CHECK (precio_unitario >= 0),
    CONSTRAINT detalles_pedido_pedido_fkey
        FOREIGN KEY (idpedidos)
        REFERENCES public.pedidos (idpedidos)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT detalles_pedido_producto_fkey
        FOREIGN KEY (idproductos)
        REFERENCES public.productos (idproductos)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,
    CONSTRAINT detalles_pedido_pedido_producto_key
        UNIQUE (idpedidos, idproductos)
);

CREATE INDEX IF NOT EXISTS productos_categoria_id_idx
    ON public.productos (categoria_id);

CREATE INDEX IF NOT EXISTS pedidos_cliente_id_idx
    ON public.pedidos (cliente_id);

CREATE INDEX IF NOT EXISTS detalles_pedido_idpedidos_idx
    ON public.detalles_pedido (idpedidos);

CREATE INDEX IF NOT EXISTS detalles_pedido_idproductos_idx
    ON public.detalles_pedido (idproductos);

COMMIT;
