<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{

    public function run(): void
    {
        DB::statement("INSERT IGNORE INTO 
                        productos(nombre, descripcion, precio, stock, categoria_id, image_url, codigo_producto) 
                      VALUES 
                      ('MEMORIA RAM DDR5',
                      'DE 8GB CON FRECUENCIA DE 3200MHZ LATENCIA CL20',
                      100,
                      10,
                      3,
                      'https://i.postimg.cc/BbHS5BJG/ddr5.jpg',
                      'SKU-001'),
                      ('MEMORIA RAM DDR5',
                      'DE 16GB CON FRECUENCIA DE 3200MHZ LATENCIA CL20',
                      600,
                      2,
                      3,
                      'https://i.postimg.cc/BbHS5BJG/ddr5.jpg',
                      'SKU-002'),
                      ('MEMORIA RAM DDR5',
                      'DE 32GB CON FRECUENCIA DE 3200MHZ LATENCIA CL20',
                      1000,
                      2,
                      3,
                      'https://i.postimg.cc/BbHS5BJG/ddr5.jpg',
                      'SKU-003'),
                      ('MEMORIA RAM DDR4',
                      'DE 8GB CON FRECUENCIA DE 3200MHZ  Tipo SODIMM LATENCIA CL20',
                      250,
                      2,
                      3,
                      'https://i.postimg.cc/3wYvkWCR/DDR4.png',
                      'SKU-004'),
                      ('MEMORIA RAM DDR4',
                      'DE 16GB CON FRECUENCIA DE 3200MHZ  Tipo SODIMM LATENCIA CL20',
                      500,
                      2,
                      3,
                      'https://i.postimg.cc/3wYvkWCR/DDR4.png',
                      'SKU-005'),
                      ('MEMORIA RAM DDR4',
                      'DE 32GB CON FRECUENCIA DE 3200MHZ  Tipo SODIMM LATENCIA CL20',
                      900,
                      2,
                      3,
                      'https://i.postimg.cc/3wYvkWCR/DDR4.png',
                      'SKU-006'),
                      ('LAPTOP VICTUS',
                      'LAPTOP VICTUS 16.1 RYZEN 5 5600H 8GB 512GB SSD RADEON RX5500M FREEDOS, COLOR NEGRO',
                      9000,
                      5,
                      1,
                      'https://i.postimg.cc/Y2Fs5Sny/victus.png',
                      'SKU-007'),
                      ('LAPTOP LENOVO',
                      'Laptop ThinkPad E16 Gen 2 Core Ultra 5-125U 16GB RAM + 512GB SSD 16 Win11 Pro en Español Negro',
                      11000,
                      5,
                      1,
                      'https://i.postimg.cc/Hx18h3Px/LENOVO.jpg',
                      'SKU-008'),
                      ('LAPTOP ACER NITRO 5',
                      'Laptop Nitro 5 AN515-55 i5-10300H8GB Memoria RAM DDR4 + 512GB SSD de 15.6 Win10 Home NVidia GTX 1650',
                      8000,
                      5,
                      1,
                      'https://i.postimg.cc/NGWkw791/acer.jpg',
                      'SKU-009'),
                      ('TECLA RAZER',
                      'TECLA RAZER NEGRO PARA TECLADOS GAMING RC21-01490100-R3M1',
                      150,
                      15,
                      4,
                      'https://i.postimg.cc/zBLw4kb1/tecla.jpg',
                      'SKU-010'),
                      ('TECLA RAZER',
                      'TECLA RAZER QUARTZ ROSADO PARA TECLADOS GAMING RC21-01490300-R3M1',
                      150,
                      15,
                      4,
                      'https://i.postimg.cc/W4c6xZmJ/tecla-raz-pbtqr.jpg',
                      'SKU-011'),
                      ('TECLA RAZER',
                      'TECLA RAZER VERDE PARA TECLADOS GAMING RC21-01490400-R3M1',
                      150,
                      15,
                      4,
                      'https://i.postimg.cc/sDSJmK7j/tecla-raz-pbtv.jpg',
                      'SKU-012'),
                      ('TECLADO',
                      'Mini Teclado Inalambrico Marca Manhattan Modelo 180764 En Espanol Color Negro',
                      300,
                      5,
                      4,
                      'https://i.postimg.cc/DwpmX3ZD/wlt-mh-180764e.jpg',
                      'SKU-013'),
                      ('TECLADO',
                      'Kit De Teclado Y Mouse Optico Inalambricos Marca Manhattan Modelo 180771 Color Negro En Espanol',
                      120,
                      5,
                      4,
                      'https://i.postimg.cc/QthLNHDN/tmwl-mh-180771e.jpg',
                      'SKU-014'),
                      ('Mouse',
                      'MOUSE MANHATTAN 177801 EDGE OPTICO 3BOTONES C/SCROLL AZUL USB',
                      60,
                      5,
                      4,
                      'https://i.postimg.cc/8CWJQnp2/mou-mh-e7801a.jpg',
                      'SKU-015'),
                      ('Monitor',
                      'Monitor LED AOC 27 Pulgadas G2790VX 144hz Plano delgado',
                      1000,
                      5,
                      2,
                      'https://i.postimg.cc/NfXRw4sL/1713312485.png',
                      'SKU-016'),
                      ('Monitor',
                      'Monitor Samsung Odyssey G3 de 24 pulgadas FHD a 180hz',
                      1600,
                      5,
                      2,
                      'https://i.postimg.cc/Hs09fg4h/1732550702.png',
                      'SKU-017'),
                      ('Monitor',
                      'Monitor Asus TUF VG249Q3A 23.8 Pulgadas Fast IPS 180Hz',
                      1700,
                      5,
                      2,
                      'https://i.postimg.cc/5tDzX7SD/1725580795.png',
                      'SKU-018'),
                      ('SSD',
                      'Unidad De Estado Solido Marca Kingston Modelo M.2 NV3 Capacidad De 2TB',
                      1270,
                      5,
                      5,
                      'https://i.postimg.cc/bNX9dJww/ssd-kn-nv32tm2.jpg',
                      'SKU-019'),
                      ('SSD',
                      'Unidad De Estado Solido Marca Kingston Modelo KC600 Factor De Forma 2.5 Capacidad De 1024GB SKC600/1024G',
                      1070,
                      5,
                      5,    
                      'https://i.postimg.cc/Rhmq5jv4/ssd-kn-kc601024.jpg',
                      'SKU-020'),
                      ('SSD',
                      'UNIDAD ESTADO SOLIDO SSD CRUCIAL MX500 2.5 250GB CT250MX500SSD1',
                      370,
                      5,
                      5,
                      'https://i.postimg.cc/J00vnhrP/ssd-cru-mx50025.jpg',
                      'SKU-021'),
                      ('AUDIFONOS',
                      'Audifonos Marca Logitech Modelo H390 Conexion USB Con Microfono Color Blanco',
                      215,
                      5,
                      6,
                      'https://i.postimg.cc/G2tnBKzN/au.png',
                      'SKU-022'),
                      ('AUDIFONOS',
                      'Redmi Buds 6 Play Audífonos Bluetooth - Azul',
                      110,
                      5,
                      6,
                      'https://i.postimg.cc/fbLMXMRf/Redmi-Buds6-Play-Azul1200x1200-1-700x700.jpg',
                      'SKU-023'),
                      ('AUDIFONOS',
                      'AIR Audífonos Bluetooth con ENC y Autonomía de 7 Horas - Gris',
                      300,
                      5,
                      6,
                      'https://i.postimg.cc/8khg77bG/QCY-AIR-GR-1200x1200-1-700x700.jpg',
                      'SKU-024')

                      ", );
                     

    }
}
